### DISCUSSION TITLE
Apache X Table with SnowFlake Tables Error: Could not find or load main class org.apache.xtable.utilities.RunSync

### DISCUSSION THREAD

**Discussion by soumilshah1995** [apache/incubator-xtable#500] [General]
I hope you're doing well. I'm following your blog and successfully set up Snowflake. I configured roles and an external volume on Snowflake, created a table, and saw the table on S3 following your guide: [How to Interoperate with Snowflake and Open Table Formats](https://medium.com/@sagarlakshmipathy/how-to-interoperate-with-snowflake-and-open-table-formats-e70f453787a2).
I downloaded all the jar files mentioned in your blog:

```
wget -O ./iceberg-spark-runtime-3.2_2.12-1.4.2.jar https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.2_2.12/1.4.2/iceberg-spark-runtime-3.2_2.12-1.4.2.jar
wget -O ./snowflake-jdbc-3.13.28.jar https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.28/snowflake-jdbc-3.13.28.jar
wget -O ./iceberg-aws-1.4.2.jar https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws/1.4.2/iceberg-aws-1.4.2.jar
wget -O ./bundle-2.23.9.jar https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.23.9/bundle-2.23.9.jar

```
Additionally, I downloaded the X Table jar file and I then defined my my_config.yaml as follows:
```
sourceFormat: ICEBERG

targetFormats:
  - DELTA
datasets:
  -
    tableBasePath: s3://soumilshah-dev-1995/snowflake_tables/iceberg_people
    tableDataPath: s3://soumilshah-dev-1995/snowflake_tables/iceberg_people/data
    tableName: iceberg_people
    namespace: tempeh.public
```

## Sync Command 

```
java -cp "iceberg-spark-runtime-3.2_2.12-1.4.2.jar:utilities-0.1.0-beta1-bundled.jar:snowflake-jdbc-3.13.28.jar:iceberg-aws-1.4.2.jar:bundle-2.23.9.jar" org.apache.xtable.utilities.RunSync  --datasetConfig my_config.yaml

```

Error: Could not find or load main class org.apache.xtable.utilities.RunSync

## Snowflake 
![image](https://github.com/user-attachments/assets/e061bfc0-5b49-4af9-b470-41fa2c8e7aa3)

![image](https://github.com/user-attachments/assets/886f6bb6-31d7-4192-a8af-8864e381f1ce)

I have issue with x table sync with snowflake can someone help
