### ISSUE TITLE
AWS Glue with Iceberg Source and Delta Target

### ISSUE THREAD

**Issue by ForeverAngry** [apache/incubator-xtable#354]
I seem to keep getting a `version-hint.text` error when trying to use the .jar file to sync an existing iceberg table to a delta, using AWS Glue as my catalog.  Im using the `my_config.yaml` file as directed in the doc's, but i feel like im missing something.

For instance:
```
sourceFormat: ICEBERG
targetFormats:
  - DELTA
datasets:
  -
   # (i have this set to the parent path that holds the (metadata, data and _delta_log directories), ive tried other configurations as well.  The _delta_log directory gets created, but nothing gets created in it, as i keep getting the error indicated above)
    tableBasePath: s3://path
    tableName: my_table
```

Do i need to create a catalog.yaml and clients.yaml file as well?  I noticed these but i thought they were only for implementing custom sources other than Hudi, Iceberg or Delta.

Thanks in advance!
